export type PriceFormat = "fisso" | "da" | "preventivo";

export interface Servizio {
  id: string;
  title: string;
  desc: string;
  price: number | null;
  originalPrice: number | null;
  active: boolean;
  slug?: string;
  priceFormat?: PriceFormat;
}

export const DEFAULT_PREZZI: Servizio[] = [
  {
    id: "730",
    title: "Dichiarazione 730",
    desc: "Compilazione e invio della dichiarazione dei redditi modello 730.",
    price: 50,
    originalPrice: 79,
    active: true,
    slug: "dichiarazione-730",
  },
  {
    id: "730-avanzato",
    title: "Dichiarazione 730 avanzata",
    desc: "730 con casi complessi: redditi esteri, ristrutturazioni/superbonus, bonus multipli, immobili all'estero, redditi da trading. Onorario studio tarato sulla complessità reale.",
    price: 98,
    originalPrice: null,
    active: true,
    slug: "dichiarazione-730-avanzato",
  },
  {
    id: "upf-base",
    title: "Modello Redditi PF (UPF) base",
    desc: "Dichiarazione Modello Redditi Persone Fisiche per chi non può usare il 730: ex titolari P.IVA cessata, redditi fondiari multipli, redditi assimilati che escludono il 730.",
    price: 98,
    originalPrice: null,
    active: true,
    slug: "dichiarazione-upf-base",
  },
  {
    id: "upf-avanzato",
    title: "Modello Redditi PF (UPF) avanzata",
    desc: "UPF con quadri complessi: RW (conti/cripto esteri), RT plusvalenze, redditi esteri con credito d'imposta, IVIE/IVAFE, P.IVA cessata con strascichi pluriennali. Onorario tarato sulla complessità reale.",
    price: 198,
    originalPrice: null,
    active: true,
    slug: "dichiarazione-upf-avanzato",
  },
  {
    id: "apertura-prof-sola",
    title: "Apertura P.IVA Professionista (solo apertura)",
    desc: "Apertura Partita IVA professionista (gestione separata INPS o cassa privata) come servizio una tantum: scelta codice ATECO, regime fiscale e cassa. Senza contabilità annuale inclusa e senza rinnovo tacito.",
    price: 146.40,
    originalPrice: null,
    active: true,
    slug: "apertura-professionista-sola",
  },
  {
    id: "piva-prof",
    title: "Apertura P.IVA Professionista forfettario + contabilita annuale",
    desc: "Apertura P.IVA forfettario + contabilita annuale fino a 20 fatture + dichiarazione redditi + EFAT. Rinnovo annuale, prezzo bloccato 3 anni se scegli la formula triennale.",
    price: 549,
    originalPrice: null,
    active: true,
    slug: "piva-professionista",
  },
  {
    id: "piva-prof-semp",
    title: "Apertura P.IVA Professionista semplificata + contabilita annuale",
    desc: "Apertura P.IVA regime semplificato/ordinario + contabilita annuale + IVA periodica + dichiarazione redditi + EFAT. Per professionisti con ricavi attesi oltre 85.000 euro o con spese rilevanti da portare in deduzione.",
    price: 1610.40,
    originalPrice: null,
    active: true,
    slug: "piva-professionista-semplificato",
    priceFormat: "da",
  },
  {
    id: "piva-art",
    title: "Apertura P.IVA Artigiano/Commerciante",
    desc: "Apertura Partita IVA con iscrizione CCIAA, INPS artigiani/commercianti, SIA. Rimborsi spese e tributi pubblici separati.",
    price: 610,
    originalPrice: null,
    active: true,
    slug: "piva-artigiano-commerciante",
  },
  {
    id: "piva-art-forf",
    title: "Apertura P.IVA Artigiano/Commerciante forfettario + contabilità annuale",
    desc: "Bundle tutto incluso: apertura + CCIAA + SIA + INPS + 12 mesi contabilità forfettario + EFAT. Onorario studio, tributi e diritti pubblici separati.",
    price: 1220,
    originalPrice: null,
    active: true,
    slug: "piva-artigiano-commerciante-forfettario",
    priceFormat: "da",
  },
  {
    id: "piva-art-semp",
    title: "Apertura P.IVA Artigiano/Commerciante semplificato + contabilità annuale",
    desc: "Bundle apertura + CCIAA + SIA + INPS + 12 mesi contabilità semplificata/ordinaria con IVA periodica + EFAT. Per chi prevede ricavi oltre 85.000 euro o ha spese rilevanti da dedurre. Onorario studio, tributi e diritti pubblici separati.",
    price: 2074,
    originalPrice: null,
    active: true,
    slug: "piva-artigiano-commerciante-semplificato",
    priceFormat: "da",
  },
  {
    id: "cont-prof-forf",
    title: "Contabilita annuale P.IVA Professionista forfettario",
    desc: "Gestione contabile annuale per chi ha gia aperto P.IVA forfettaria e vuole cambiare commercialista. Fino a 20 fatture, redditi PF, EFAT inclusa. Rinnovo annuale.",
    price: 402.60,
    originalPrice: null,
    active: true,
    slug: "contabilita-professionista-forfettario",
  },
  {
    id: "cont-prof-semp",
    title: "Contabilita annuale P.IVA Professionista semplificata",
    desc: "Gestione contabile annuale con IVA periodica e redditi PF per chi ha gia P.IVA in regime semplificato o ordinario. EFAT inclusa. Rinnovo annuale.",
    price: 1464,
    originalPrice: null,
    active: true,
    slug: "contabilita-professionista-semplificata",
    priceFormat: "da",
  },
  {
    id: "cont-art-forf",
    title: "Contabilita annuale P.IVA Artigiano/Commerciante forfettario",
    desc: "Gestione contabile forfettaria + INPS artigiani/commercianti + adempimenti CCIAA annuali + redditi PF + EFAT. Per chi ha gia P.IVA attiva. Rinnovo annuale.",
    price: 610,
    originalPrice: null,
    active: true,
    slug: "contabilita-artigiano-forfettario",
    priceFormat: "da",
  },
  {
    id: "cont-art-semp",
    title: "Contabilita annuale P.IVA Artigiano/Commerciante semplificata",
    desc: "Gestione contabile semplificata/ordinaria + IVA periodica + INPS artigiani + CCIAA + redditi PF + EFAT. Per chi ha gia P.IVA oltre 85.000 euro. Rinnovo annuale.",
    price: 1464,
    originalPrice: null,
    active: true,
    slug: "contabilita-artigiano-semplificata",
    priceFormat: "da",
  },
  {
    id: "consulenza",
    title: "Consulenza su misura",
    desc: "Analisi personalizzata e piano d'azione per la tua situazione specifica.",
    price: null,
    originalPrice: null,
    active: true,
  },
];
